CREATE EXTENSION IF NOT EXISTS CITEXT;
CREATE EXTENSION IF NOT EXISTS PG_TRGM;

CREATE TABLE IF NOT EXISTS users (
    id UUID DEFAULT GEN_RANDOM_UUID() PRIMARY KEY,
    name TEXT NOT NULL,
    email CITEXT NOT NULL UNIQUE,
    password BYTEA NOT NULL,
    last_online TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    online BOOLEAN DEFAULT FALSE NOT NULL,
    activated BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    version INT NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS idx_users_id ON users(id);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_name_trgm ON users USING GIN (name GIN_TRGM_OPS);
CREATE INDEX if NOT EXISTS idx_users_email_trgm ON users USING GIN (name GIN_TRGM_OPS);